### ISSUE TITLE
Selling a Full pass to someone who doesn't want dinner

### ISSUE THREAD

**Issue by bardsley** [bardsley/merseysidelatinfestival#55]
If someone buys a ticket but doesn't want dinner but the full pass is STILL cheaper without dinner

Client doesn't ask for meal preferences and sends meal preferences as all -1

This stop lambda dev-checkout_complete from invoking dev-create-ticket [logs from a failure](https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fdev-checkout_complete)

**Comment by bardsley** [comment]
This still needs to be considered but actually the lambda is broken even for all options set

**Comment by connorkm2** [comment]
> This still needs to be considered but actually the lambda is broken even for all options set

Fixed the error which was breaking everything. But we do need to decide on the "didn't ask for dinner" option. Can also be used for artist pass when they don't want dinner. 

Either we add an extra attribute to the table called 'meal_active' or we add that to the _meal_preferences_ and set it to false for passes without dinner and false for passes with dinner even if they don't want it. 

Or we assign another number like -2 for this scenario.

**Comment by connorkm2** [comment]
This could be added as an option for everyone to say "I don't want dinner".

**Comment by bardsley** [comment]
I think it has been fixed

**Comment by bardsley** [comment]
I like that as an idea, do we need a different choice value of -2 so someone can say I don't wantr a starter or a new preference?
